Makes HasQualifierParameter an inherited type; Fixes #3831
typetools/checker-framework pull request #3832
Opened 2020-10-25 04:16 UTC by t-rasmud

2020-10-25 16:59 UTC, mernst requested changes
I don't see a test case that shows that `@HasQualifierParameter` is inherited when not written explicitly.  Could you add one?

How is this related to #3400?

2020-10-25 16:59 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/qual/HasQualifierParameter.java
> +import java.lang.annotation.*;
Our style is to not use wildcard imports.  Please just add one import statement.

2020-10-26 16:46 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/qual/NoQualifierParameter.java
>   * @see HasQualifierParameter
This annotation should be inherited, too.

2020-10-26 23:42 UTC, t-rasmud commented
> How is this related to #3400?
This PR addresses the first requirement of #3400:  "If a class extends a `@HasQualifierParameter` class (or implements a `@HasQualifierParameter` interface), then that class must also be marked `@HasQualifierParameter`."
It does not address the second requirement: "A particular subclass should be able to specify which qualifier parameter should be used for the super class."

2020-10-27 17:27 UTC, mernst requested changes
Maybe I missed it, but still I don't see the test case that I asked about:

> I don't see a test case that shows that @HasQualifierParameter is inherited when not written explicitly. Could you add one?

I see that there in an unannotated subclass:
```class SubNoQualifierParameter extends InheritNoQualifierParameter {}```
but I don't see a test that confirms that the class `SubNoQualifierParameter` is treated as having a qualifier parameter.

2020-10-27 18:29 UTC, t-rasmud commented
> Maybe I missed it, but still I don't see the test case that I asked about:
> 
> > I don't see a test case that shows that @HasQualifierParameter is inherited when not written explicitly. Could you add one?
> 
> I see that there in an unannotated subclass:
> `class SubNoQualifierParameter extends InheritNoQualifierParameter {}`
> but I don't see a test that confirms that the class `SubNoQualifierParameter` is treated as having a qualifier parameter.

I have now added tests that confirm `SubHasQualifierParameter` is treated as having a qualifier parameter and `SubNoQualifierParameter` is treated as not having a qualifier parameter.

2020-10-27 18:48 UTC, mernst approved these changes

2020-10-27 18:49 UTC, mernst commented
> > How is this related to #3400?
> 
> This PR addresses the first requirement of #3400: "If a class extends a `@HasQualifierParameter` class (or implements a `@HasQualifierParameter` interface), then that class must also be marked `@HasQualifierParameter`."
> It does not address the second requirement: "A particular subclass should be able to specify which qualifier parameter should be used for the super class."

When this PR lands, please add a note at #3400 to explain what has been done and what remains to be done. Thanks!

2020-10-28 17:25 UTC, merged

2020-10-28 18:45 UTC, t-rasmud commented
@mernst That was an oversight on my part. @smillst Could you please re-open the PR if there are more changes? Thanks.