Infer `@MonotonicNonNull`, `@EnsuresNonNull`, and `@RequiresNonNull`
typetools/checker-framework pull request #3955
Opened 2020-12-01 18:29 UTC by mernst

Review supertypes before subtypes, to see specificationss for newly-added methods.

Merge with https://github.com/typetools/annotation-tools/pull/326

2020-12-02 18:08 UTC, smillst requested changes
Could you add test for this?

2020-12-02 18:08 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
> +            if (member instanceof VariableElement) {
Instead of `instanceof` you can use `ElementFilter.fieldsIn(containingClass.getEnclosedElements()` as the expression in the foreach.

2020-12-02 18:08 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
> +            AnnotatedTypeMirror atm = convertCFAbstractValueToAnnotatedTypeMirror(v, atf);
`convertCFAbstractValueToAnnotatedTypeMirror` creates a partially-annotation AnnotatedTypeMirror which can cause crashes if passed to isSubtype or leastUpperBound or anywhere the framework expects fully annotated types.  Instead,  `convertCFAbstractValueToAnnotatedTypeMirror` should make a copy of `fieldType` and change its primary annotations to those in `v`.

2020-12-04 19:42 UTC, mernst commented
@smillst This is ready for re-review.

2020-12-04 23:46 UTC, smillst requested changes

2020-12-04 23:46 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> +     * @param elt element for a field
Is `elt` always a field declared in the same class as the method is declared?

2020-12-04 23:46 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> +     * Return the string representation of a precondition annotation for the given field.
It's not clear how to convert from field to a precondition annotation.  Can you expand this comment?

2020-12-04 23:46 UTC, smillst commented on checker/src/main/java/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.java
> +                return "@org.checkerframework.checker.nullness.qual.EnsuresNonNull(\""
I think this should be `...EnsuresNonNull("this.` for clarity.

2020-12-04 23:46 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceScenes.java
> +            FieldAccess fa = entry.getKey();
I think `fa` could be an access of field that other than a field of "this".  For example, "other.field" is a field access that would appear in the store.  I don't think the code currently handles a contract involving a field not declared in "this".  (There should at least be a test for this.)

2020-12-10 15:13 UTC, mernst commented
Temporarily closing.

2020-12-10 15:13 UTC, closed without merging