Use terminology "annotation file" in preference to "stub file"
typetools/checker-framework pull request #4034
Opened 2020-12-16 19:34 UTC by mernst

2020-12-16 21:35 UTC, jwaataja requested changes
When renaming `stubAnnos` parameters, I added comments where the javadoc needs to be updated. However, since this parameter will become a field shortly, it may be unnecessary to fix it if it's not worth the effort.

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
> +                // We didn't find the files.
This is in a method `parseStubFiles`, so saying `stub` here makes sense. Same comment applies to rest of method.

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> + * last two arguments. It operates in two steps. First, it calls the Stub Parser to parse a stub
I think now it only side-effects the last argument rather than the last two. Also, on this comment can also change "stub" to "annotation file".

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file".

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileParser.java
> +     * @param annotationFileAnnos annotations from the stub file; side-effected by this method
"stub file" -> "annotation file"

2020-12-16 21:35 UTC, jwaataja commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileResource.java
> +/** Interface for annotation files (stub files). */
Same comment as <https://github.com/jwaataja/checker-framework/pull/1>. Retain usage of word "source".

2020-12-16 21:59 UTC, mernst commented
@jwaataja Could you re-review?   If you approve this, I will merge it into master and then into your `ajava2` branch.  Thanks.

2020-12-17 02:14 UTC, jwaataja approved these changes
One of the comments from last applied to more areas. I've left comments at those points, and once those are addressed this looks good.

2020-12-17 02:51 UTC, merged