Make OffsetDependentTypesHelper use standardizeString
typetools/checker-framework pull request #4197
Opened 2021-01-23 21:26 UTC by mernst

Merge after #4195.  (Can review now without its diffs.)

2021-01-25 18:04 UTC, kelloggm requested changes
I only reviewed the parts that aren't in #4195

2021-01-25 18:04 UTC, kelloggm commented on framework/src/main/java/org/checkerframework/common/value/ValueCheckerUtils.java
> +     * Optimize the given JavaExpression, using Value Checker annotations.
`Optimize` is a vague name. I think I'm fine with it here as the name of this method - it conveys the right intuition for what this method does - but this Javadoc needs to define it. I think the specific meaning here is "constant fold any parts of the given expression that the factory has exact values for", based on reading the code.

2021-01-26 22:26 UTC, smillst approved these changes
Does this fix https://github.com/typetools/checker-framework/issues/3475?

2021-01-26 22:26 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/value/ValueCheckerUtils.java
> +            ClassName e = (ClassName) je;
This cast and assignment aren't needed.

2021-01-26 23:29 UTC, mernst commented
> Does this fix #3475?

Not quite.  There is still one difference in `OffsetDependentTypesHelper`.  I think that code can be moved into the superclass in a future pull request.

2021-01-27 17:51 UTC, merged