Correct Javadoc of GenericAnnotatedTypeFactory#parseJavaExpressionString
typetools/checker-framework pull request #4238
Opened 2021-02-04 22:41 UTC by smillst

2021-02-07 03:12 UTC, mernst requested changes

2021-02-07 03:12 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> +     * identifiers as if they were written in Java code that {@code currentPath}.
This is not grammatical.  Should "that" be "at"?

2021-02-07 03:12 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/GenericAnnotatedTypeFactory.java
> +     * @param currentPath the path to use to resolve identifiers
What does it mean to resolve an identifier?  It seems to be a different concept than the "resolve" in `resolveMethods`.

2021-02-11 23:18 UTC, smillst commented
I'm going to fix this Javadoc when removing `useLocalScope`, so I'm closing this.

2021-02-11 23:18 UTC, closed without merging