If javac issues an error, don't type check any file.
typetools/checker-framework pull request #4352
Opened 2021-03-03 22:48 UTC by smillst

This prevents the framework from crashing on ill-formed elements from source files that did not compile.

Fixes https://github.com/typetools/checker-framework/issues/4041.

2021-03-04 16:02 UTC, mernst commented
Please see code review comments in #4354.

2021-03-04 22:29 UTC, smillst commented on checker/tests/nullness/java-unsound/Figure1.java
> +// @skip-test no need to test for the javac error.
I kept these test files because they are examples in the paper.

2021-03-05 18:40 UTC, smillst commented
@mernst this is ready to be reviewed again.  I think we need to pass `-AsuppressWarnings=type.checking.not.run` to the wpiPlumeLib test that is failing, but I can't figure out how to do so.  Can you take a look?

2021-03-05 19:54 UTC, mernst requested changes

2021-03-05 19:55 UTC, mernst commented
> I think we need to pass `-AsuppressWarnings=type.checking.not.run` to the wpiPlumeLib test that is failing

I agree.

wpi.sh [permits](https://checkerframework.org/manual/#wpi-one) you to pass arguments.  If you run it as `wpi.sh -b SOMEARG ...` then it will run `gradlew compileJava SOMEARG` on the target program.

I don't know how to pass a command-line argument to `gradlew compileJava` so that `-AsuppressWarnings=type.checking.not.run` is passed to `javac`.

@smillst @kelloggm do you have suggestions?  Does this require an enhancement to do-like-javac?

2021-03-05 21:37 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
> +        if (shouldSuppress(getSuppressWarningsStringsFromOption(), errKey)) {
Yes, I've done so here https://github.com/typetools/checker-framework/pull/4364.

2021-03-05 22:51 UTC, mernst approved these changes
The changes are OK with me, modulo that the tests must pass (which is gradle hacking that @smillst and @kelloggm are better qualified for).

2021-03-08 22:50 UTC, kelloggm commented
@mernst @smillst the capability to pass arguments to javac when using dljc's wpi tool existed already, but was undocumented. I've corrected that error here: https://github.com/kelloggm/do-like-javac/pull/17 (the PR is already merged, so you should be able to use it right away). 

You should be able to get this PR working by adding this code to the invocation of `wpi.sh` in `test-wpi-plumelib.sh` anytime after the `--`:
```
--extraJavacArgs='-AsuppressWarnings=type.checking.not.run'
```

Sorry for the inconvenience.

2021-03-09 17:10 UTC, merged