Fix crash in ajava-based WPI related to captures
typetools/checker-framework pull request #5335
Opened 2022-09-23 21:14 UTC by kelloggm

I'm fairly confident that there is a better way to do this than catching the `ClassCastException`, but I was worried of the performance implications of calling `asSuper` on every inference of a field's type, since only very rarely will the two `AnnotatedTypeMirror` not actually have the same actual Java class (causing the exception).

Technically, their `kind` is the same - they are both typevars - so it cannot be checked that way, even though the underlying Java class of one is `AnnotatedDeclaredType`. I think it's probably bad that `updateAtmWithLub` directly casts to `AnnotatedTypeVariable`, but I'm not sure how else it could work.

2022-09-23 21:50 UTC, smillst commented
> Technically, their kind is the same - they are both typevars - so it cannot be checked that way, even though the underlying Java class of one is AnnotatedDeclaredType. I think it's probably bad that updateAtmWithLub directly casts to AnnotatedTypeVariable, but I'm not sure how else it could work.

Are you saying there's an `AnnotatedDelcaredType` that returns `TYPEVAR` when `getKind` is called?  If so, that needs to be fix.

2022-09-23 21:58 UTC, smillst requested changes

2022-09-23 21:58 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
> +    // happen for example when a local variable of type ? extends T is assigned to a
A local variable can't have a wildcard type.  I think you when an expression has type `? extends T`.

2022-09-26 14:31 UTC, kelloggm commented
> Are you saying there's an `AnnotatedDelcaredType` that returns `TYPEVAR` when getKind is called? If so, that needs to be fix.

I think that is what's happening. I've added debug code to the `catch` block in this PR so that you can see for yourself (by running `./gradlew ainferIndexAjavaTest -Pemit.test.debug`). That prints out something like this every time the exception is caught:
```
    Catching a ClassCastException: java.lang.ClassCastException: class org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType cannot be cast to class org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable (org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedDeclaredType and org.checkerframework.framework.type.AnnotatedTypeMirror$AnnotatedTypeVariable are in unnamed module of loader 'app')
    The cast must be one of the following two AnnotatedTypeMirrors. The type to cast to is decided by the kind of rhsATM.
    rhsATM: capture#40 extends T extends Object
    rhsATM.getKind(): TYPEVAR
    atmFromStorage: T extends Object
    atmFromStorage.getKind(): TYPEVAR
```

I have no idea where the bad `AnnotatedTypeMirror` is coming from - I'm not sure even where to start looking to debug that. My goal with this PR was to treat the symptom of this problem so that I can run WPI without a crash 🙃  However, I agree this seems like it breaks one of our invariants for the CF as a whole.

2022-09-28 14:28 UTC, kelloggm commented on framework/src/main/java/org/checkerframework/common/wholeprograminference/WholeProgramInferenceImplementation.java
> +      System.out.println(
You were exactly right - thanks for figuring this out! I'm glad there wasn't a deeper problem, and I've now written a proper fix.

2022-09-28 15:10 UTC, smillst approved these changes

2022-09-28 17:46 UTC, kelloggm commented
@smillst I'll need you to review this again: the tests for the version you approved earlier today failed for a good reason: the check did the wrong thing if one of the arguments to `updateAtmWithLub` was a null type. With this improved handling of type variable bounds in `updateAtmWithLub`, I was also able to remove another workaround for a similar problem that I added a few months ago.

2022-09-28 18:20 UTC, smillst approved these changes

2022-09-28 22:49 UTC, merged