Pass `TypeMirror` to `QualifierHierarchy.isSubtype()`
typetools/checker-framework pull request #5896
Opened 2023-05-19 19:05 UTC by mernst

Merge after:
 * #5893
 * #5894

2023-05-22 19:03 UTC, smillst requested changes
I have not yet reviewed all the callsites of the new methods.  I have a few comments on the implementations of the new methods.

Also, I'm concerned that the new methods are not tested because they currently ignore the type mirrors.  I have a found a few places where I think the wrong TypeMirror is passed, but there's no way to add a test to verify.  Can you add the code that changes the behavior of isSubtype if the one of the Java types are non-relevent ?

2023-05-23 15:36 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/QualifierHierarchy.java
> +    return isSubtype(subQualifier, superQualifier);
I explained this in a comment.  We can remove the method rather than deprecating it if you prefer.

2023-05-23 15:36 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/QualifierHierarchy.java
> +  default boolean isSubtype(
I removed the overloads.

2023-05-23 18:25 UTC, smillst commented
> > Can you add the code that changes the behavior of isSubtype if the one of the Java types are non-relevent ?
> 
> That is in #5862.

Where?  I expected some override of the new `isSubtype` method to do something with that passed `TypeMirror`s but I don't see any.

2023-05-24 16:49 UTC, closed without merging