Don't try to parse empty files
typetools/checker-framework pull request #6056
Opened 2023-06-26 15:08 UTC by mernst

Fixes #6053

2023-06-26 15:14 UTC, msridhar commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
> +  @SuppressWarnings("builder:required.method.not.called")
Should we add a comment explaining this suppression?

2023-06-26 15:38 UTC, smillst approved these changes

2023-06-26 16:02 UTC, msridhar requested changes
Sorry, still curious about the RLC suppression

2023-06-27 10:10 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/stub/AnnotationFileElementTypes.java
> +      "builder:required.method.not.called" //  `allFiles` contains multiple references to a resource
I have updated the comment.  Could you take another look?  Thanks.

2023-06-27 16:33 UTC, msridhar approved these changes

2023-06-27 16:33 UTC, merged