Jar files are shadowed centrally
typetools/checker-framework pull request #6065
Opened 2023-06-29 15:11 UTC by mernst

2023-06-29 15:37 UTC, smillst requested changes

2023-06-29 15:37 UTC, smillst commented on dataflow/build.gradle
> +  // See the comment in ../build.gradle in the shadowJar block.
It has to be shaded in task `createDataflowShaded` below, too.

2023-06-29 15:37 UTC, smillst commented on javacutil/build.gradle
> +  // If you add an external dependency, you must shadow its packages.
This change is correct.

2023-07-03 02:26 UTC, mernst commented
@smillst Could you go ahead and write this correctly?  Thanks.

2023-07-03 16:29 UTC, smillst commented
I've made this change https://github.com/typetools/checker-framework/pull/6074.

2023-07-03 16:29 UTC, closed without merging