Suppress new Error Prone warning
typetools/checker-framework pull request #6120
Opened 2023-08-03 16:09 UTC by smillst

2023-08-03 16:26 UTC, mernst approved these changes

2023-08-03 17:28 UTC, msridhar commented
@mernst @smillst if you build releases of the Checker Framework on JDK 17, you may want to fix this issue rather than suppressing; see my comment [above](https://github.com/typetools/checker-framework/pull/6120#discussion_r1283478919).  I'm going to turn off the auto-merge just to let you confirm.

2023-08-03 17:39 UTC, smillst commented
> @mernst @smillst if you build releases of the Checker Framework on JDK 17, you may want to fix this issue rather than suppressing; see my comment [above](https://github.com/typetools/checker-framework/pull/6120#discussion_r1283478919). I'm going to turn off the auto-merge just to let you confirm.

Thanks for pointing this out and the further explanation.  We do build the release with JDK 17, so I fixed it so that all the calls to `getEnclosedElement` are on variables with static type of `Symbol`.

2023-08-03 17:44 UTC, msridhar requested changes

2023-08-03 17:44 UTC, msridhar commented on framework/src/main/java/org/checkerframework/common/reflection/DefaultReflectionResolver.java
> +      for (Symbol s : sym.getEnclosedElements()) {
It looks like `classSym` gets updated on each loop iteration? Not sure this will behave the same as the previous code.

2023-08-03 19:51 UTC, msridhar approved these changes
Now LGTM.  If I get time, I may try to improve the Error Prone check so that you don't need to suppress in cases like this one (as calls to `Symbol.getEnclosedElements()` are ok).

2023-08-03 20:22 UTC, merged

2023-08-03 20:27 UTC, mernst commented
@msridhar Thanks for your insight on this issue.
For future reference, when enabling auto-squash-and-merge, please remove the crufty per-commit-message list from the squashed commit message.  Thanks!

2023-08-03 21:31 UTC, msridhar commented
> @msridhar Thanks for your insight on this issue.
> For future reference, when enabling auto-squash-and-merge, please remove the crufty per-commit-message list from the squashed commit message. Thanks!

@mernst sure, sorry about that.  If you like, there are new defaults that we can set for the project when it comes to squashed commit messages.  See below, which is under the Settings for the repo:

-------------------
<img width="538" alt="Screenshot 2023-08-03 at 14 29 47" src="https://github.com/typetools/checker-framework/assets/193105/e6c5609b-1a54-4fd8-b8aa-ee4ec6a72c99">

--------------------

My preference is "Default to pull request title and description."  Then, the PR description (if any) will be used as the body of the commit message.

2023-08-04 16:47 UTC, smillst commented
@msridhar I changed the default to "Default to pull request title and description."  Thanks for pointing out this option!