Correct Java type of conditional expressions in dataflow.
typetools/checker-framework pull request #6307
Opened 2023-11-15 18:26 UTC by smillst

2023-11-15 18:32 UTC, mernst approved these changes
Thanks!

2023-11-16 16:10 UTC, smillst commented
@mernst I had to re-do the implementation because I had not accounted for CFValue subclasses.  Could you re-review?

2023-11-16 17:23 UTC, mernst requested changes

2023-11-16 17:23 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java
> +   * @return the least upper bound of this and {@code other}
Above it says "an upper bound", here it says "the least upper bound".  Please clarify.
Also, please write a comment discussing the relationship between this method and `leastUpperBound`.

2023-11-17 16:33 UTC, msridhar commented on framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java
> +   * {@code other}, but it does not have be to the leaster upper bound.
Small typo here:
```suggestion
   * {@code other}, but it does not have be to the least upper bound.
```

2023-11-17 16:58 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java
> +   * {@code other}, but it does not have be to the leaster upper bound.
Thanks!

2023-11-24 17:59 UTC, mernst requested changes

2023-11-24 17:59 UTC, mernst commented on checker/src/main/java/org/checkerframework/checker/nullness/KeyForValue.java
> +    KeyForValue lub = super.upperBound(other, upperBoundTypeMirror, shouldWiden);
This variable name suggests that `upperBound()` actually returns the least upper bound.  Why is `least` not in its name?

OK, I see now.  I wonder if its name should be `leastUpperBoundOrWiden()`, for clarity.

2023-11-24 17:59 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/flow/CFAbstractTransfer.java
> +      TypeMirror ternaryType = TreeUtils.typeOf(n.getTree());
It's a bit inconsistent to use "contitional" in the comment but "ternary" in the variable name.

2023-11-24 17:59 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/flow/CFAbstractValue.java
> +   * @param shouldWiden true if the lub should perform widening
It's not really a lub.

2023-11-24 17:59 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/util/AtmLubVisitor.java
> +    TypeMirror otherTM = otherType.getUnderlyingType();
Is this logically part of this pull request?  Should it be committed in a separate PR?

2023-11-29 00:18 UTC, mernst approved these changes

2023-11-29 03:26 UTC, merged