Improve documentation of commonAssignmentCheck and correct overrides
typetools/checker-framework pull request #6347
Opened 2023-12-08 20:26 UTC by smillst

2023-12-08 21:22 UTC, mernst requested changes
I have a few questions.

2023-12-08 21:22 UTC, mernst commented on framework/src/main/java/org/checkerframework/common/aliasing/AliasingVisitor.java
> -  @FormatMethod
Why is this removed?

2023-12-08 21:22 UTC, mernst commented on checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanVisitor.java
> -        // Print the messages because super isn't called.
Why is this removed?

2023-12-08 21:22 UTC, mernst commented on framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> +   * this method is overridden, then the first then should call {@link
Could you clarify this?

2023-12-08 21:22 UTC, mernst commented on framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> +   * <p>Subclasses should override this method if in all cases unless the tree for the {@code
Grammar issue here.

2023-12-08 21:22 UTC, mernst commented on framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> +          "%s %s (at %s): actual tree = %s %s%n   expected: %s %s%n",
Why is this labeled "expected"?  That doesn't seem to fit with `shouldSkipUses(ExpressionTree)`.

2024-01-16 20:15 UTC, mernst commented
@smillst A ping in case this fell through the cracks.  It isn't urgent, though.

2026-03-03 17:53 UTC, mernst commented
@smillst Ping.

2026-04-09 16:16 UTC, smillst commented on checker/src/main/java/org/checkerframework/checker/index/inequality/LessThanVisitor.java
> -        // Print the messages because super isn't called.
The method that was overridden changed so and super does not call these methods.

2026-04-09 16:17 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/aliasing/AliasingVisitor.java
> -  @FormatMethod
Because this isn't a FormatMethod.

2026-04-09 19:25 UTC, merged