Rewrite BoundsInitializer
typetools/checker-framework pull request #6445
Opened 2024-02-07 16:10 UTC by smillst

Fixes #6373

2024-02-16 21:02 UTC, mernst requested changes
I have some questions that can be clarified in documentation.
Thanks!

2024-02-16 21:02 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
> +        typeVariableMap.put(t, annotatedTypeVariable);
Is method `initializeTypeVariable` only ever called once?  If not, then this seems to be redoing work and overwriting a value in the map.  I have the same question for the method below, `initializeWildcard`.

2024-02-16 21:06 UTC, mernst commented on framework/src/main/java/org/checkerframework/framework/type/BoundsInitializer.java
>  public class BoundsInitializer {
I wonder whether "BoundsInitializer" is the right name for this.  It copies the structure of a type (more specifically, a type variable or wildcard) into an AnnotatedTypeMirror.  Could the name reflect its behavior?  "Initializer" is not very evocative.

2024-02-27 16:26 UTC, smillst commented on framework/src/main/java/org/checkerframework/framework/type/AnnotatedTypeMirror.java
> +        }
None of the methods in `AnnotatedTypeMirror` add annotations to their component types.

2024-02-28 22:11 UTC, mernst submitted a review, later dismissed

2024-03-01 17:51 UTC, mernst approved these changes
Thanks.

2024-03-01 17:52 UTC, merged