Start implementing method-level support for `skipDefs` flag
typetools/checker-framework pull request #6597
Opened 2024-05-13 20:20 UTC by jyoo980

2024-05-15 17:18 UTC, jyoo980 commented on framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java
> +  public boolean shouldSkipDefs(MethodTree tree) {
Instead of passing in a command-line flag, classes are able to override this method to specify which method should (or should not) be checked.

2024-05-16 14:26 UTC, mernst approved these changes

2024-05-16 16:44 UTC, smillst requested changes

2024-05-16 16:44 UTC, smillst commented on framework/src/main/java/org/checkerframework/common/basetype/BaseTypeVisitor.java
> +    ClassTree enclosingClass = TreePathUtil.enclosingClass(getCurrentPath());
Several subclasses override visitMethod and add additional warnings. Those warnings are still issued even if they should be skipped.  For visitClass, we made the method final and added `processClassTree(...)` that can be overridden by subclasses.  You should do the same for visitMethod.

2024-05-16 17:22 UTC, jyoo980 commented
@smillst I'd appreciate another review, I've made `BaseTypeVisitor#visitMethod(MethodTree, Void)` `final` and introduced `BaseTypeVisitor#processMethodTree(MethodTree)`

2024-05-16 17:28 UTC, smillst approved these changes
Thanks!

2024-05-16 21:38 UTC, merged